openapi: 3.0.0
info:
  title: libraryApplication
  version: 1.0.0
  description: '図書館アプリのライブラリ'
servers:
  - url: 'http://localhost:8080/api/v1'
    description: local Server
  - url: 'https://enigmatic-depths-14464.herokuapp.com/api/v1'
    description: Main Server
paths:
  /books:
    $ref: './paths/books.yaml#/books'
  '/books/{isbn}':
    $ref: './paths/books.yaml#/isbn'
  '/books/{isbn}/actions':
    $ref: './paths/books.yaml#/actions'
  '/lendingRecords':
    $ref: './paths/lendingRecords.yaml#/root'

